/* 
 * Mantle API
 *
 * Most endpoints require authentication with an API key.  You must first authenticate with your account by logging in your account on app.mantle.services. Then, you will need to navigate to the \"My API Key\" page in the Administration section. You might need to have the user administrator of your organization generate you an API Key first.  You must then use this API Key in all your requests with the following header:  [ x-api-key: API_KEY ].
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = mantle.lib.Client.SwaggerDateConverter;

namespace mantle.lib.Model
{
    /// <summary>
    /// Batch
    /// </summary>
    [DataContract]
    public partial class Batch :  IEquatable<Batch>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Batch" /> class.
        /// </summary>
        /// <param name="DividedBatch">DividedBatch.</param>
        /// <param name="RemainingAmount">RemainingAmount.</param>
        /// <param name="Date">Date.</param>
        /// <param name="BatchTransactionId">BatchTransactionId.</param>
        public Batch(List<Batch> DividedBatch = default(List<Batch>), long? RemainingAmount = default(long?), DateTime? Date = default(DateTime?), string BatchTransactionId = default(string))
        {
            this.DividedBatch = DividedBatch;
            this.RemainingAmount = RemainingAmount;
            this.Date = Date;
            this.BatchTransactionId = BatchTransactionId;
        }
        
        /// <summary>
        /// Gets or Sets DividedBatch
        /// </summary>
        [DataMember(Name="dividedBatch", EmitDefaultValue=false)]
        public List<Batch> DividedBatch { get; set; }

        /// <summary>
        /// Gets or Sets RemainingAmount
        /// </summary>
        [DataMember(Name="remainingAmount", EmitDefaultValue=false)]
        public long? RemainingAmount { get; set; }

        /// <summary>
        /// Gets or Sets Date
        /// </summary>
        [DataMember(Name="date", EmitDefaultValue=false)]
        public DateTime? Date { get; set; }

        /// <summary>
        /// Gets or Sets BatchTransactionId
        /// </summary>
        [DataMember(Name="batchTransactionId", EmitDefaultValue=false)]
        public string BatchTransactionId { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class Batch {\n");
            sb.Append("  DividedBatch: ").Append(DividedBatch).Append("\n");
            sb.Append("  RemainingAmount: ").Append(RemainingAmount).Append("\n");
            sb.Append("  Date: ").Append(Date).Append("\n");
            sb.Append("  BatchTransactionId: ").Append(BatchTransactionId).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as Batch);
        }

        /// <summary>
        /// Returns true if Batch instances are equal
        /// </summary>
        /// <param name="input">Instance of Batch to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(Batch input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.DividedBatch == input.DividedBatch ||
                    this.DividedBatch != null &&
                    this.DividedBatch.SequenceEqual(input.DividedBatch)
                ) && 
                (
                    this.RemainingAmount == input.RemainingAmount ||
                    (this.RemainingAmount != null &&
                    this.RemainingAmount.Equals(input.RemainingAmount))
                ) && 
                (
                    this.Date == input.Date ||
                    (this.Date != null &&
                    this.Date.Equals(input.Date))
                ) && 
                (
                    this.BatchTransactionId == input.BatchTransactionId ||
                    (this.BatchTransactionId != null &&
                    this.BatchTransactionId.Equals(input.BatchTransactionId))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.DividedBatch != null)
                    hashCode = hashCode * 59 + this.DividedBatch.GetHashCode();
                if (this.RemainingAmount != null)
                    hashCode = hashCode * 59 + this.RemainingAmount.GetHashCode();
                if (this.Date != null)
                    hashCode = hashCode * 59 + this.Date.GetHashCode();
                if (this.BatchTransactionId != null)
                    hashCode = hashCode * 59 + this.BatchTransactionId.GetHashCode();
                return hashCode;
            }
        }
    }

}
