/* 
 * Mantle API
 *
 * Most endpoints require authentication with an API key.  You must first authenticate with your account by logging in your account on app.mantle.services. Then, you will need to navigate to the \"My API Key\" page in the Administration section. You might need to have the user administrator of your organization generate you an API Key first.  You must then use this API Key in all your requests with the following header:  [ x-api-key: API_KEY ].
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = mantle.lib.Client.SwaggerDateConverter;

namespace mantle.lib.Model
{
    /// <summary>
    /// InvitationCreateRequest
    /// </summary>
    [DataContract]
    public partial class InvitationCreateRequest :  IEquatable<InvitationCreateRequest>
    {
        /// <summary>
        /// Defines Roles
        /// </summary>
        [JsonConverter(typeof(StringEnumConverter))]
        public enum RolesEnum
        {
            
            /// <summary>
            /// Enum MCKeeperAdmin for value: MCKeeperAdmin
            /// </summary>
            [EnumMember(Value = "MCKeeperAdmin")]
            MCKeeperAdmin = 1,
            
            /// <summary>
            /// Enum MCBilling for value: MCBilling
            /// </summary>
            [EnumMember(Value = "MCBilling")]
            MCBilling = 2,
            
            /// <summary>
            /// Enum MCUserAdmin for value: MCUserAdmin
            /// </summary>
            [EnumMember(Value = "MCUserAdmin")]
            MCUserAdmin = 3,
            
            /// <summary>
            /// Enum MCTrackerAdmin for value: MCTrackerAdmin
            /// </summary>
            [EnumMember(Value = "MCTrackerAdmin")]
            MCTrackerAdmin = 4,
            
            /// <summary>
            /// Enum MCTrackerUser for value: MCTrackerUser
            /// </summary>
            [EnumMember(Value = "MCTrackerUser")]
            MCTrackerUser = 5,
            
            /// <summary>
            /// Enum MCAuthenticityUser for value: MCAuthenticityUser
            /// </summary>
            [EnumMember(Value = "MCAuthenticityUser")]
            MCAuthenticityUser = 6
        }


        /// <summary>
        /// Gets or Sets Roles
        /// </summary>
        [DataMember(Name="roles", EmitDefaultValue=false)]
        public List<RolesEnum> Roles { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="InvitationCreateRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected InvitationCreateRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="InvitationCreateRequest" /> class.
        /// </summary>
        /// <param name="Email">Email (required).</param>
        /// <param name="Roles">Roles.</param>
        public InvitationCreateRequest(string Email = default(string), List<RolesEnum> Roles = default(List<RolesEnum>))
        {
            // to ensure "Email" is required (not null)
            if (Email == null)
            {
                throw new InvalidDataException("Email is a required property for InvitationCreateRequest and cannot be null");
            }
            else
            {
                this.Email = Email;
            }
            this.Roles = Roles;
        }
        
        /// <summary>
        /// Gets or Sets Email
        /// </summary>
        [DataMember(Name="email", EmitDefaultValue=false)]
        public string Email { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class InvitationCreateRequest {\n");
            sb.Append("  Email: ").Append(Email).Append("\n");
            sb.Append("  Roles: ").Append(Roles).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as InvitationCreateRequest);
        }

        /// <summary>
        /// Returns true if InvitationCreateRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of InvitationCreateRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(InvitationCreateRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Email == input.Email ||
                    (this.Email != null &&
                    this.Email.Equals(input.Email))
                ) && 
                (
                    this.Roles == input.Roles ||
                    this.Roles != null &&
                    this.Roles.SequenceEqual(input.Roles)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Email != null)
                    hashCode = hashCode * 59 + this.Email.GetHashCode();
                if (this.Roles != null)
                    hashCode = hashCode * 59 + this.Roles.GetHashCode();
                return hashCode;
            }
        }
    }

}
