/* 
 * Mantle API
 *
 * Most endpoints require authentication with an <strong>API key</strong><br><br>                                         You must first authenticate with your account by logging in your account on <strong><a target='_blank' href='https://www.mantleblockchain.com'/>mantleblockchain.com</a></strong>.<br>                                         Then, you will need to navigate to the <strong>My API Key</strong> page in the Settings section.<br>                                         You need to have the role administrator of your organization to generate an <strong>API Key</strong>.<br><br>                                         Then use this <strong>API Key</strong> in all your requests with the following header:<br><br>                                         <strong>[ x-api-key: API_KEY ]</strong><br><br>For more information on the different product and more, you can refer to the <a target='_blank' href='https://docs.mantleblockchain.com/v1.0/documentation/home'><strong>knowledge base</strong></a>
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = mantle.lib.Client.SwaggerDateConverter;

namespace mantle.lib.Model
{
    /// <summary>
    /// IssuedBatchesResponse
    /// </summary>
    [DataContract]
    public partial class IssuedBatchesResponse :  IEquatable<IssuedBatchesResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IssuedBatchesResponse" /> class.
        /// </summary>
        /// <param name="assetDisplayName">assetDisplayName.</param>
        /// <param name="batches">batches.</param>
        public IssuedBatchesResponse(string assetDisplayName = default(string), List<AssetTransaction> batches = default(List<AssetTransaction>))
        {
            this.AssetDisplayName = assetDisplayName;
            this.Batches = batches;
        }
        
        /// <summary>
        /// Gets or Sets AssetDisplayName
        /// </summary>
        [DataMember(Name="assetDisplayName", EmitDefaultValue=false)]
        public string AssetDisplayName { get; set; }

        /// <summary>
        /// Gets or Sets Batches
        /// </summary>
        [DataMember(Name="batches", EmitDefaultValue=false)]
        public List<AssetTransaction> Batches { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class IssuedBatchesResponse {\n");
            sb.Append("  AssetDisplayName: ").Append(AssetDisplayName).Append("\n");
            sb.Append("  Batches: ").Append(Batches).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as IssuedBatchesResponse);
        }

        /// <summary>
        /// Returns true if IssuedBatchesResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of IssuedBatchesResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(IssuedBatchesResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.AssetDisplayName == input.AssetDisplayName ||
                    (this.AssetDisplayName != null &&
                    this.AssetDisplayName.Equals(input.AssetDisplayName))
                ) && 
                (
                    this.Batches == input.Batches ||
                    this.Batches != null &&
                    this.Batches.SequenceEqual(input.Batches)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.AssetDisplayName != null)
                    hashCode = hashCode * 59 + this.AssetDisplayName.GetHashCode();
                if (this.Batches != null)
                    hashCode = hashCode * 59 + this.Batches.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
