/* 
 * Mantle API
 *
 * Most endpoints require authentication with an API key.  You must first authenticate with your account by logging in your account on app.mantle.services. Then, you will need to navigate to the \"My API Key\" page in the Administration section. You might need to have the user administrator of your organization generate you an API Key first.  You must then use this API Key in all your requests with the following header:  [ x-api-key: API_KEY ].
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = mantle.lib.Client.SwaggerDateConverter;

namespace mantle.lib.Model
{
    /// <summary>
    /// SealerBreadcrumbingCompareResponse
    /// </summary>
    [DataContract]
    public partial class SealerBreadcrumbingCompareResponse :  IEquatable<SealerBreadcrumbingCompareResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SealerBreadcrumbingCompareResponse" /> class.
        /// </summary>
        /// <param name="Accuracy">Accuracy.</param>
        /// <param name="FileUrl">FileUrl.</param>
        /// <param name="ChangedText">ChangedText.</param>
        public SealerBreadcrumbingCompareResponse(double? Accuracy = default(double?), string FileUrl = default(string), List<string> ChangedText = default(List<string>))
        {
            this.Accuracy = Accuracy;
            this.FileUrl = FileUrl;
            this.ChangedText = ChangedText;
        }
        
        /// <summary>
        /// Gets or Sets Accuracy
        /// </summary>
        [DataMember(Name="accuracy", EmitDefaultValue=false)]
        public double? Accuracy { get; set; }

        /// <summary>
        /// Gets or Sets FileUrl
        /// </summary>
        [DataMember(Name="fileUrl", EmitDefaultValue=false)]
        public string FileUrl { get; set; }

        /// <summary>
        /// Gets or Sets ChangedText
        /// </summary>
        [DataMember(Name="changedText", EmitDefaultValue=false)]
        public List<string> ChangedText { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SealerBreadcrumbingCompareResponse {\n");
            sb.Append("  Accuracy: ").Append(Accuracy).Append("\n");
            sb.Append("  FileUrl: ").Append(FileUrl).Append("\n");
            sb.Append("  ChangedText: ").Append(ChangedText).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SealerBreadcrumbingCompareResponse);
        }

        /// <summary>
        /// Returns true if SealerBreadcrumbingCompareResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of SealerBreadcrumbingCompareResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SealerBreadcrumbingCompareResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Accuracy == input.Accuracy ||
                    (this.Accuracy != null &&
                    this.Accuracy.Equals(input.Accuracy))
                ) && 
                (
                    this.FileUrl == input.FileUrl ||
                    (this.FileUrl != null &&
                    this.FileUrl.Equals(input.FileUrl))
                ) && 
                (
                    this.ChangedText == input.ChangedText ||
                    this.ChangedText != null &&
                    this.ChangedText.SequenceEqual(input.ChangedText)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Accuracy != null)
                    hashCode = hashCode * 59 + this.Accuracy.GetHashCode();
                if (this.FileUrl != null)
                    hashCode = hashCode * 59 + this.FileUrl.GetHashCode();
                if (this.ChangedText != null)
                    hashCode = hashCode * 59 + this.ChangedText.GetHashCode();
                return hashCode;
            }
        }
    }

}
