/* 
 * Mantle API
 *
 * Most endpoints require authentication with an API key.  You must first authenticate with your account by logging in your account on app.mantle.services. Then, you will need to navigate to the \"My API Key\" page in the Administration section. You might need to have the user administrator of your organization generate you an API Key first.  You must then use this API Key in all your requests with the following header:  [ x-api-key: API_KEY ].
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = mantle.lib.Client.SwaggerDateConverter;

namespace mantle.lib.Model
{
    /// <summary>
    /// TrackerStatsResponse
    /// </summary>
    [DataContract]
    public partial class TrackerStatsResponse :  IEquatable<TrackerStatsResponse>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackerStatsResponse" /> class.
        /// </summary>
        /// <param name="TransactionCount">TransactionCount.</param>
        /// <param name="Volume">Volume.</param>
        /// <param name="ActiveUsers">ActiveUsers.</param>
        public TrackerStatsResponse(int? TransactionCount = default(int?), double? Volume = default(double?), int? ActiveUsers = default(int?))
        {
            this.TransactionCount = TransactionCount;
            this.Volume = Volume;
            this.ActiveUsers = ActiveUsers;
        }
        
        /// <summary>
        /// Gets or Sets TransactionCount
        /// </summary>
        [DataMember(Name="transactionCount", EmitDefaultValue=false)]
        public int? TransactionCount { get; set; }

        /// <summary>
        /// Gets or Sets Volume
        /// </summary>
        [DataMember(Name="volume", EmitDefaultValue=false)]
        public double? Volume { get; set; }

        /// <summary>
        /// Gets or Sets ActiveUsers
        /// </summary>
        [DataMember(Name="activeUsers", EmitDefaultValue=false)]
        public int? ActiveUsers { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TrackerStatsResponse {\n");
            sb.Append("  TransactionCount: ").Append(TransactionCount).Append("\n");
            sb.Append("  Volume: ").Append(Volume).Append("\n");
            sb.Append("  ActiveUsers: ").Append(ActiveUsers).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TrackerStatsResponse);
        }

        /// <summary>
        /// Returns true if TrackerStatsResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of TrackerStatsResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TrackerStatsResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.TransactionCount == input.TransactionCount ||
                    (this.TransactionCount != null &&
                    this.TransactionCount.Equals(input.TransactionCount))
                ) && 
                (
                    this.Volume == input.Volume ||
                    (this.Volume != null &&
                    this.Volume.Equals(input.Volume))
                ) && 
                (
                    this.ActiveUsers == input.ActiveUsers ||
                    (this.ActiveUsers != null &&
                    this.ActiveUsers.Equals(input.ActiveUsers))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.TransactionCount != null)
                    hashCode = hashCode * 59 + this.TransactionCount.GetHashCode();
                if (this.Volume != null)
                    hashCode = hashCode * 59 + this.Volume.GetHashCode();
                if (this.ActiveUsers != null)
                    hashCode = hashCode * 59 + this.ActiveUsers.GetHashCode();
                return hashCode;
            }
        }
    }

}
