/* 
 * Mantle API
 *
 * Most endpoints require authentication with an API key.  You must first authenticate with your account by logging in your account on app.mantle.services. Then, you will need to navigate to the \"My API Key\" page in the Administration section. You might need to have the user administrator of your organization generate you an API Key first.  You must then use this API Key in all your requests with the following header:  [ x-api-key: API_KEY ].
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = mantle.lib.Client.SwaggerDateConverter;

namespace mantle.lib.Model
{
    /// <summary>
    /// TrackerBatchTransferRequest
    /// </summary>
    [DataContract]
    public partial class TrackerBatchTransferRequest :  IEquatable<TrackerBatchTransferRequest>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackerBatchTransferRequest" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected TrackerBatchTransferRequest() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="TrackerBatchTransferRequest" /> class.
        /// </summary>
        /// <param name="RecipientEmail">RecipientEmail (required).</param>
        /// <param name="Amount">Amount.</param>
        /// <param name="AssetId">AssetId (required).</param>
        /// <param name="BatchIds">BatchIds (required).</param>
        public TrackerBatchTransferRequest(string RecipientEmail = default(string), int? Amount = default(int?), string AssetId = default(string), List<string> BatchIds = default(List<string>))
        {
            // to ensure "RecipientEmail" is required (not null)
            if (RecipientEmail == null)
            {
                throw new InvalidDataException("RecipientEmail is a required property for TrackerBatchTransferRequest and cannot be null");
            }
            else
            {
                this.RecipientEmail = RecipientEmail;
            }
            // to ensure "AssetId" is required (not null)
            if (AssetId == null)
            {
                throw new InvalidDataException("AssetId is a required property for TrackerBatchTransferRequest and cannot be null");
            }
            else
            {
                this.AssetId = AssetId;
            }
            // to ensure "BatchIds" is required (not null)
            if (BatchIds == null)
            {
                throw new InvalidDataException("BatchIds is a required property for TrackerBatchTransferRequest and cannot be null");
            }
            else
            {
                this.BatchIds = BatchIds;
            }
            this.Amount = Amount;
        }
        
        /// <summary>
        /// Gets or Sets RecipientEmail
        /// </summary>
        [DataMember(Name="recipientEmail", EmitDefaultValue=false)]
        public string RecipientEmail { get; set; }

        /// <summary>
        /// Gets or Sets Amount
        /// </summary>
        [DataMember(Name="amount", EmitDefaultValue=false)]
        public int? Amount { get; set; }

        /// <summary>
        /// Gets or Sets AssetId
        /// </summary>
        [DataMember(Name="assetId", EmitDefaultValue=false)]
        public string AssetId { get; set; }

        /// <summary>
        /// Gets or Sets BatchIds
        /// </summary>
        [DataMember(Name="batchIds", EmitDefaultValue=false)]
        public List<string> BatchIds { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class TrackerBatchTransferRequest {\n");
            sb.Append("  RecipientEmail: ").Append(RecipientEmail).Append("\n");
            sb.Append("  Amount: ").Append(Amount).Append("\n");
            sb.Append("  AssetId: ").Append(AssetId).Append("\n");
            sb.Append("  BatchIds: ").Append(BatchIds).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as TrackerBatchTransferRequest);
        }

        /// <summary>
        /// Returns true if TrackerBatchTransferRequest instances are equal
        /// </summary>
        /// <param name="input">Instance of TrackerBatchTransferRequest to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(TrackerBatchTransferRequest input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.RecipientEmail == input.RecipientEmail ||
                    (this.RecipientEmail != null &&
                    this.RecipientEmail.Equals(input.RecipientEmail))
                ) && 
                (
                    this.Amount == input.Amount ||
                    (this.Amount != null &&
                    this.Amount.Equals(input.Amount))
                ) && 
                (
                    this.AssetId == input.AssetId ||
                    (this.AssetId != null &&
                    this.AssetId.Equals(input.AssetId))
                ) && 
                (
                    this.BatchIds == input.BatchIds ||
                    this.BatchIds != null &&
                    this.BatchIds.SequenceEqual(input.BatchIds)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.RecipientEmail != null)
                    hashCode = hashCode * 59 + this.RecipientEmail.GetHashCode();
                if (this.Amount != null)
                    hashCode = hashCode * 59 + this.Amount.GetHashCode();
                if (this.AssetId != null)
                    hashCode = hashCode * 59 + this.AssetId.GetHashCode();
                if (this.BatchIds != null)
                    hashCode = hashCode * 59 + this.BatchIds.GetHashCode();
                return hashCode;
            }
        }
    }

}
